// Command ouigen converts the vendored IEEE registries
// (third_party/ieee-oui, captured by cmd/ouifetch) into
// internal/oui/table.txt: one "PREFIX<tab>vendor" line per assignment,
// prefixes as uppercase hex nibbles of length 6 (MA-L /24), 7 (MA-M
// /28) or 9 (MA-S /36), names folded to 7-bit ASCII. The generated
// table lives under the repo-wide ascii gate; only the vendored CSVs
// are exempt.
//
// -verify (run by presubmit, offline) regenerates in memory and
// requires a byte-identical committed table, and re-validates the
// vendored CSVs as strict UTF-8 -- so the ascii exemption can never
// quietly admit junk, and table and capture cannot drift apart.
package main

import (
	"bytes"
	"encoding/csv"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode/utf8"
)

const (
	srcDir    = "third_party/ieee-oui"
	tablePath = "internal/oui/table.txt"
)

// prefixLen maps the CSV Registry column to the assignment's expected
// hex-nibble count: /24, /28, /36.
var prefixLen = map[string]int{"MA-L": 6, "MA-M": 7, "MA-S": 9}

// conflicts counts registry rows that re-assign an already-seen prefix
// to a different organization (real in the IEEE data; first row wins).
var conflicts int

func main() {
	fs := flag.NewFlagSet("ouigen", flag.ContinueOnError)
	verify := fs.Bool("verify", false, "check committed table + capture instead of writing")
	if err := fs.Parse(os.Args[1:]); err != nil {
		if err == flag.ErrHelp {
			os.Exit(0)
		}
		os.Exit(2) // flag already printed the message and usage
	}

	table := map[string]string{}
	for _, name := range []string{"oui.csv", "mam.csv", "oui36.csv"} {
		if err := load(filepath.Join(srcDir, name), table); err != nil {
			fatal("%v", err)
		}
	}
	out := render(table)

	if *verify {
		committed, err := os.ReadFile(tablePath)
		if err != nil {
			fatal("read %s: %v", tablePath, err)
		}
		if !bytes.Equal(committed, out) {
			fatal("%s is stale -- rerun: go run ./cmd/ouigen", tablePath)
		}
		fmt.Printf("ouigen: OK (%d prefixes, %d registry conflicts first-won)\n", len(table), conflicts)
		return
	}
	if err := os.WriteFile(tablePath, out, 0o644); err != nil {
		fatal("write %s: %v", tablePath, err)
	}
	fmt.Printf("ouigen: wrote %s (%d prefixes, %d registry conflicts first-won)\n", tablePath, len(table), conflicts)
}

// load parses one vendored registry CSV into table. It also enforces
// the capture contract on the committed file (strict UTF-8, no stray
// control bytes) -- the check-ascii exemption for third_party/ieee-oui
// is only sound because this runs in every presubmit.
func load(path string, table map[string]string) error {
	raw, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	if !utf8.Valid(raw) {
		return fmt.Errorf("%s: not valid UTF-8", path)
	}
	for _, r := range string(raw) {
		if r < 0x20 && r != '\n' && r != '\t' {
			return fmt.Errorf("%s: control byte %#x", path, r)
		}
	}
	rd := csv.NewReader(bytes.NewReader(raw))
	rd.FieldsPerRecord = -1 // trailing-column slop in some registry rows
	recs, err := rd.ReadAll()
	if err != nil {
		return fmt.Errorf("%s: %v", path, err)
	}
	if len(recs) == 0 || len(recs[0]) < 3 || recs[0][1] != "Assignment" {
		return fmt.Errorf("%s: unexpected header", path)
	}
	for i, rec := range recs[1:] {
		if len(rec) < 3 {
			return fmt.Errorf("%s row %d: %d fields", path, i+2, len(rec))
		}
		want, ok := prefixLen[rec[0]]
		if !ok {
			return fmt.Errorf("%s row %d: unknown registry %q", path, i+2, rec[0])
		}
		prefix := strings.ToUpper(strings.TrimSpace(rec[1]))
		if len(prefix) != want || strings.Trim(prefix, "0123456789ABCDEF") != "" {
			return fmt.Errorf("%s row %d: assignment %q is not %d hex nibbles", path, i+2, rec[1], want)
		}
		name := asciiFold(rec[2])
		if name == "" {
			name = "(unnamed)"
		}
		// The registries really do contain conflicting assignments
		// (080030 was famously handed out three times in the 1980s);
		// first row wins, deterministically, and the count is reported.
		if prev, dup := table[prefix]; dup {
			if prev != name {
				conflicts++
			}
			continue
		}
		table[prefix] = name
	}
	return nil
}

func render(table map[string]string) []byte {
	prefixes := make([]string, 0, len(table))
	for p := range table {
		prefixes = append(prefixes, p)
	}
	sort.Strings(prefixes)
	b := &strings.Builder{}
	fmt.Fprintf(b, "# GENERATED by cmd/ouigen from third_party/ieee-oui -- do not edit.\n")
	fmt.Fprintf(b, "# PREFIX<tab>vendor; prefix nibble count encodes the block size (6=/24 7=/28 9=/36).\n")
	for _, p := range prefixes {
		fmt.Fprintf(b, "%s\t%s\n", p, table[p])
	}
	return []byte(b.String())
}

// foldMap covers the Latin diacritics that actually occur in vendor
// names; anything else non-ASCII becomes "?". Deliberately dumb and
// dependency-free -- x/text would do this "properly" at the cost of
// the module's zero-dependency property.
// Escapes, not literal runes: this file itself sits inside the ascii
// gate.
var foldMap = map[rune]string{
	'\u00c0': "A", '\u00c1': "A", '\u00c2': "A", '\u00c3': "A", '\u00c4': "A", '\u00c5': "A",
	'\u00c7': "C", '\u00c8': "E", '\u00c9': "E", '\u00ca': "E", '\u00cb': "E",
	'\u00cc': "I", '\u00cd': "I", '\u00ce': "I", '\u00cf': "I", '\u00d1': "N",
	'\u00d2': "O", '\u00d3': "O", '\u00d4': "O", '\u00d5': "O", '\u00d6': "O", '\u00d8': "O",
	'\u00d9': "U", '\u00da': "U", '\u00db': "U", '\u00dc': "U", '\u00dd': "Y",
	'\u00df': "ss",
	'\u00e0': "a", '\u00e1': "a", '\u00e2': "a", '\u00e3': "a", '\u00e4': "a", '\u00e5': "a",
	'\u00e7': "c", '\u00e8': "e", '\u00e9': "e", '\u00ea': "e", '\u00eb': "e",
	'\u00ec': "i", '\u00ed': "i", '\u00ee': "i", '\u00ef': "i", '\u00f1': "n",
	'\u00f2': "o", '\u00f3': "o", '\u00f4': "o", '\u00f5': "o", '\u00f6': "o", '\u00f8': "o",
	'\u00f9': "u", '\u00fa': "u", '\u00fb': "u", '\u00fc': "u", '\u00fd': "y", '\u00ff': "y",
	'\u0152': "OE", '\u0153': "oe", '\u0160': "S", '\u0161': "s", '\u017d': "Z", '\u017e': "z",
	'\u2013': "-", '\u2014': "-", '\u2018': "'", '\u2019': "'", '\u201c': "\"", '\u201d': "\"",
}

// asciiFold renders a vendor name in 7-bit ASCII: whitespace collapsed,
// known diacritics folded, everything else non-ASCII replaced by "?".
func asciiFold(s string) string {
	b := &strings.Builder{}
	for _, r := range s {
		switch {
		case r == '\t' || r == '\n':
			b.WriteByte(' ')
		case r >= 0x20 && r < 0x7f:
			b.WriteRune(r)
		default:
			if f, ok := foldMap[r]; ok {
				b.WriteString(f)
			} else {
				b.WriteByte('?')
			}
		}
	}
	return strings.Join(strings.Fields(b.String()), " ")
}

func fatal(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "ouigen: "+format+"\n", args...)
	os.Exit(1)
}
